### ISSUE TITLE
2 Positions with the same coordinates

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#199] opened 2024-06-24 17:19 UTC
Seems you have a space coordinate for a planet, that should not be possible.

![image](https://github.com/sirgwain/craig-stars/assets/170196074/d5662dbe-8fa4-4f01-a77f-bce308943a5f)

**Comment by sirgwain** [comment] 2024-10-01 14:59
closing as duplicate of https://github.com/sirgwain/craig-stars/issues/198

**Closed as completed by sirgwain** 2024-10-01 14:59 UTC
Labels: bug
